name: 'Setup PostgreSQL'
description: 'Setup a PostgreSQL database'
author: 'Lolfoollor'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  # See https://hub.docker.com/_/postgres for supported versions
  # and further details on input environment variables
  postgresql version:
    description: 'Version of PostgreSQL to use'
    required: false
    default: 'latest'
  postgresql db:
    description: 'POSTGRES_DB - name for the default database that is created'
    required: false
    default: ''
  postgresql user:
    description: 'POSTGRES_USER - create the specified user with superuser power'
    required: false
    default: ''
  postgresql password:
    description: 'POSTGRES_PASSWORD - superuser password'
    required: false
    default: ''
  HOST_PORT:
    description: 'POSTGRES_HOST_PORT - host port to connect to postgres port'
    required: false
    default: 5432
  CONTAINER_PORT:
    description: 'POSTGRES_CONTAINER_PORT - container port for the host port to connect to'
    required: false
    default: 5432
runs:
  using: 'docker'
  image: 'Dockerfile'
